/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:03c44017-5daa-4c5f-8a42-950a13f136b5",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_yx9Hs6q82",
    "aws_user_pools_web_client_id": "50b970ftc9nuko6hcetbf27v5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gddn7cpzmjcx7jqszh4iemoi3a.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kydacfo7qbakpgopsu2b3scsga",
    "aws_user_files_s3_bucket": "notesbucket143212-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
